---
OrdererOrgs:
  - Name: example.com
    Domain: example.com
    Specs:
      - Hostname: orderer1
        SANS:
          - 192.168.1.107

PeerOrgs:
  - Name: org0.example.com
    Domain: org0.example.com
    EnableNodeOUs: true
    CA:
      Hostname: ca
      CommonName: ca.org0.example.com
      Country: US
      Province: North Carolina
      Locality: Raleigh
    Specs:
      - Hostname: peer1
        CommonName: peer1.org0.example.com
        SANS:
          - 192.168.1.107
  - Name: org1.example.com
    Domain: org1.example.com
    EnableNodeOUs: true
    CA:
      Hostname: ca
      CommonName: ca.org1.example.com
      Country: US
      Province: North Carolina
      Locality: Raleigh
    Specs:
      - Hostname: peer1
        CommonName: peer1.org1.example.com
        SANS:
          - 192.168.1.107
